### ISSUE TITLE
Compose File doesn't work

### ISSUE THREAD

**Issue by Computerdererste** [ixxoid/bacula-rpi#1]
im knew to the docker game. This documentation helped me more than the others. Nevertheless its still not perfect. I didn't knew that I have to make all the config files by hand (with the docker compose) After hours of trying to configure the config files I got it. After that I got problem with the timezone and location, because the system had no right to read the /etc/timezone... Now im able to start the containers (im also using portioner for better visualization. 

The web service have this problem Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at [no address given] to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Apache/2.4.53 (Debian) Server at 192.168.178.175 Port 9095

The port 9096 stuck in the configuration wizard seconds page with  Problem with connection to bconsole. Output=>Connecting to Director bacula-dir:9101 bconsole: message.c:1831-0 bsockcore.c:341 gethostbyname() for host "bacula-dir" failed: ERR=Name or service not known, Exitcode=>1 when hitting test

the web container have this problem
2022-06-18 20:27:08,956 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2022-06-18 20:27:08,969 INFO supervisord started with pid 1
2022-06-18 20:27:09,974 INFO spawned: 'apache2' with pid 7
2022-06-18 20:27:09,994 INFO spawned: 'php-fpm' with pid 8
2022-06-18 20:27:11,174 INFO success: apache2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

I already launched so many services before (ldap, vault warden, heimdoll, traefik, next cloud) bit bacula deffnitly is the hardest one

what can I do? what do im wrong?

**Comment by ixxoid** [comment]
I tried to clarify some more things in the documentation.
For a test to setup everything from scratch, I delted all images, containers adn volumes from bacula-rpi on my raspberry 4.
The only problem I discovered during setup with my documentation was a permission problem with the configuration file from the Baculum API. I added a description for that in the documentation.

You don't need to make all configuration files by hand. 
If you clone the repo as described, you should get a working configuration to bring all the containers up and running.
(Except the baculum API, as described above)
I'm surprized that you had permission problems to /etc/timezone. I checked the permissions on a couple of Linux systems. On all systems, the file can be read by everyone. By the way the mapping of /etc/timezone and /etc/localtime is optional.
I did this, because all the official Dcoker OS images, like Debian, Ubuntu or Fedora use UTC time. i just wanted to set up the backup schedules in my local time.
Your errors let me guess, that the configuration files in "bacula-rpi/etc" are not accessible by the conatainers.
Didn't try to set up bacula-rpi in Portainer. Maybe some extra steps are needed for using this in Portainer.
in an error situation like you have now, a clean up off the images, conainers and volumes might help.
Also sometimes if a container has an error during startup, an explicit shut down of the container might be needed.
So in such a situation I use the command "docker compose down" before i start again with "docker compose up -d"
Just to make shure, there are now "half running" containers around.
(but this is not specific to bacula-rpi)
Just courious, what OS and what hardware do you use?

**Comment by Computerdererste** [comment]
Thanks for the quick response. I think I need to set it up again with the new knowledge I gained from you. Im running the 64bit Version 10 Buster lite. I also need to try the clone thing (clone the resp). 

This fixed my timezone thing: 

#sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC 648ACFD622F3D138
#echo "deb http://deb.debian.org/debian buster-backports main" | sudo tee -a /etc/apt/sources.list.d/buster-backports.list
#sudo apt update
#sudo apt install -t buster-backports libseccomp2

Thanks a lot for your help. I will try it again

**Comment by Computerdererste** [comment]
Now it works fine! My big mistake was it to not clone the repository in work with portioner. That made the whole story to complicated for me. Thanks for your help. Great Docs from your site. Have a nice one.

**Comment by Computerdererste** [comment]
Now it works fine! My big mistake was it to not clone the repository in work with portioner. That made the whole story to complicated for me. Thanks for your help. Great Docs from your site. Have a nice one.
